package com.example.lab10.model;

import jakarta.persistence.*;

/**
 * JPA Entity representing a note in the database.
 * Maps to the "notes" table and stores note data with ownership information.

 * Database relationships:
 * - ManyToOne relationship with User entity
 * - Uses foreign key constraint on user_id column
 * - Ensures every note always has an owner
 */
@Entity
@Table(name = "notes")
public class Note {

    /**
     * Primary key for the note.
     * Automatically generated by the database using auto-increment.
     */
    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    private Integer id;

    /**
     * Title of the note.
     * Required field - cannot be null.
     */
    @Column(nullable = false)
    private String title;

    /**
     * Content/body of the note.
     * Required field - cannot be null.
     * Limited to 1000 characters maximum.
     */
    @Column(nullable = false, length = 1000)
    private String content;

    /**
     * The user who owns this note.

     * Relationship details:
     * - ManyToOne: Many notes can belong to one user
     * - optional = false: Every note MUST have an owner (cannot be null)
     * - fetch = FetchType.LAZY: User is loaded from database only when accessed
     * - @JoinColumn: Uses "user_id" as the foreign key column
     */
    // every note belongs to exactly one user
    @ManyToOne(optional = false, fetch = FetchType.LAZY)
    @JoinColumn(name = "user_id", nullable = false)
    private User owner;

    /**
     * Default no-argument constructor.
     * Required by JPA for entity instantiation.
     */
    public Note() {}

    /**
     * Constructor for creating a new note with all required fields.
     */
    public Note(String title, String content, User owner) {
        this.title = title;
        this.content = content;
        this.owner = owner;
    }

    /**
     * Gets the note ID.
     */
    public Integer getId() {
        return id;
    }

    /**
     * Gets the note title.
     */
    public String getTitle() {
        return title;
    }

    /**
     * Sets the note title.
     */
    public void setTitle(String title) {
        this.title = title;
    }

    /**
     * Gets the note content.
     */
    public String getContent() {
        return content;
    }

    /**
     * Sets the note content.
     */
    public void setContent(String content) {
        this.content = content;
    }

    /**
     * Gets the owner of this note.
     */
    public User getOwner() {
        return owner;
    }

    /**
     * Sets the owner of this note.
     */
    public void setOwner(User owner) {
        this.owner = owner;
    }
}
