package com.example.lab10.model;

import jakarta.persistence.*;

/**
 * JPA Entity representing a user account in the database.
 * Maps to the "users" table and stores authentication/authorization data.
 *
 * Security features:
 * - Passwords are stored using BCrypt hashing (never plain text)
 * - Email addresses are unique to prevent duplicate accounts
 * - Role-based authorization (ROLE_USER, ROLE_ADMIN)
 */
@Entity
@Table(name = "users")
public class User {

    /**
     * Primary key for the user.
     * Automatically generated by the database using auto-increment.
     */
    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    private Integer id;

    /**
     * Username used by Spring Security for authentication.
     * In this application, the email is stored as the username.
     * Must be unique across all users.
     */
    @Column(nullable = false, unique = true)
    private String username;

    /**
     * User's email address.
     * Must be unique and is used for login.
     */
    @Column(nullable = false, unique = true)
    private String email;

    /**
     * User's password hash.
     * Stored encrypted using BCrypt algorithm.
     * NEVER store plain text passwords.
     */
    @Column(nullable = false)
    private String password;

    /**
     * User's role for authorization.
     * Default is "ROLE_USER", can also be "ROLE_ADMIN".
     * Used by Spring Security to control access to endpoints.
     */
    @Column(nullable = false)
    private String role = "ROLE_USER";

    /**
     * Default no-argument constructor.
     * Required by JPA for entity instantiation.
     */
    public User() {
    }

    /**
     * Constructor for creating a new user with all fields.
     */
    public User(String username, String email, String password, String role) {
        this.username = username;
        this.email = email;
        this.password = password;
        this.role = role;
    }

    /**
     * Gets the user ID.
     */
    public Integer getId() {
        return id;
    }

    /**
     * Gets the username.
     */
    public String getUsername() {
        return username;
    }

    /**
     * Sets the username.
     */
    public void setUsername(String username) {
        this.username = username;
    }

    /**
     * Gets the email address.
     */
    public String getEmail() {
        return email;
    }

    /**
     * Sets the email address.
     */
    public void setEmail(String email) {
        this.email = email;
    }

    /**
     * Gets the password hash.
     */
    public String getPassword() {
        return password;
    }

    /**
     * Sets the password hash.
     * Should only be set with a properly hashed password.
     */
    public void setPassword(String password) {
        this.password = password;
    }

    /**
     * Gets the user's role.
     */
    public String getRole() {
        return role;
    }

    /**
     * Sets the user's role.
     */
    public void setRole(String role) {
        this.role = role;
    }
}
